site_name: Cursos
theme: flatly
repo_url: 'https://github.com/GomezMunera/anderson'
site_description: 'Página personal'
nav:
- 'Inicio': 'index.md'
- Materias:
  - 'Dictadas':
    - 'Cálculo Multivariable':
    - 'Sistemas de Control Continuo':
    - 'Álgebra Líneal':

  - 'Recibidas':
- Proyectos:
    - 'Red Sentir':
        - 'Clase 1': 'materias/clase1.md'

    - 'Corporación Concejo de Marinilla':
        - 'Lab 1': 'proyectos/lab1.md'

- Recursos:
    - 'Escribiendo': 'guia/Escribiendo.md'
    - 'Estilo': 'guia/estilo.md'

extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
    #- https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
    #- 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
    #- 'javascripts/extra.js'
    #- 'javascripts/MathJax.js'

# Extensions
markdown_extensions:
    - mdx_math
    - admonition
#    - codehilite:
#        linenums: true
    - footnotes
    - toc:
        permalink: true
    - pymdownx.arithmatex
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.emoji:
        emoji_generator: !!python/name:pymdownx.emoji.to_svg
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde

extra:
  language: 'es'
#  palette:
#    primary: 'indigo'
#    accent: 'indigo'
#  font:
#    text: 'Roboto'
#    code: 'Roboto Mono'
  social:
    - type: 'github'
      link: 'https://github.com/GomezMunera'
    - type: 'facebook'
      link: 'https://www.facebook.com/johnanderson.munera'
    - type: 'linkedin'
      link: 'www.linkedin.com/in/jagomezmunera'
