site_name: Cursos
theme: flatly
repo_url: 'https://github.com/GomezMunera/cursos-ing'
site_description: 'Cursos dictados en la facultad de ingeniería de la universidad de Antioquia'
nav:
- 'Inicio': 'index.md'
- Materias:
    - 'Dictadas':
        - 'Cálculo Multivariable': 'materias/clase1.md'
        - 'Sistemas de Control Continuo': 'materias/clase2.md'
        - 'Álgebra Líneal': 'materias/clase2.md'
        - 'Electrónica': 'materias/clase2.md'

    - 'Recibidas':
        - 'Lab 1': 'proyectos/lab1.md'
        - 'Lab 2': 'proyectos/lab2.md'

- Presentaciones:
    - 'Escribiendo': 'guia/Escribiendo.md'
    - 'Estilo': 'guia/estilo.md'
- Guías:
    - 'Escribiendo': 'guia/Escribiendo.md'
    - 'Estilo': 'guia/estilo.md'
extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
    #- https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
    #- 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
    #- 'javascripts/extra.js'
    #- 'javascripts/MathJax.js'



extra:
  language: 'es'
#  palette:
#    primary: 'indigo'
#    accent: 'indigo'
#  font:
#    text: 'Roboto'
#    code: 'Roboto Mono'
  social:
    - type: 'github'
      link: 'https://github.com/GomezMunera'
    - type: 'facebook'
      link: 'https://www.facebook.com/johnanderson.munera'
    - type: 'linkedin'
      link: 'www.linkedin.com/in/jagomezmunera'
